[global]
dataFrameSerialization = "legacy"

[server]
runOnSave = true
port = 8501
# Optimize for smaller datasets to reduce memory usage
maxUploadSize = 50
# Memory optimization settings
maxMessageSize = 50

[theme]
primaryColor = "#2E8B57"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[browser]
gatherUsageStats = false