[global]
dataFrameSerialization = "legacy"

[server]
runOnSave = true
port = 8501

[theme]
primaryColor = "#2E8B57"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[browser]
gatherUsageStats = false