[global]
dataFrameSerialization = "legacy"
# Performance optimization: show error details only in development
showErrorDetails = true
# Enable experimental performance features
enableStaticServing = true

[server]
runOnSave = true
port = 8501
# Performance optimization: enable faster reruns
fastReruns = true
# Reduce memory usage by enabling compression
enableCORS = false
# Optimize for larger datasets
maxUploadSize = 200

[theme]
primaryColor = "#2E8B57"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[browser]
gatherUsageStats = false